[package]
name = "rust2email"
version = "0.1.0"
authors = ["Vincent Gatine <nurelin@nurelin.eu>"]

[dependencies]
atom_syndication = "0.5.4"
clap = "2.26.0"
encoding = "0.2.33"
error-chain = "0.10.0"
html2text = "0.1.6"
lettre = "0.7.0"
lettre_email = "0.7.0"
reqwest = "0.7.3"
rss = "0.7.0"
serde = "1.0.11"
serde_derive = "1.0.11"
serde_json = "1.0.2"
slog = "2.0.6"
sloggers = "0.2.0"
toml = "0.4.5"
xdg = "2.1.0"
xml-rs = "0.6.1"

[profile.release]
lto = true
